fullnameOverride: ""
nameOverride: ""

image:
  repository: ghcr.io/thaum-xyz/containers/lvm-tools
  tag: "2025.12.18"
  pullPolicy: IfNotPresent

# Only run on nodes matching this selector
nodeSelector: {}
tolerations:
  - operator: Exists

# One device + one VG per release
lvm:
  pvDev: /dev/disk/by-partlabel/r-topolvm
  vgName: topolvm

metrics:
  enabled: true
  textfileDir: /var/lib/node_exporter
  metricsFile: lvm_diskprep.prom
  intervalSeconds: 120

prometheusRule:
  enabled: true
