apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: versitygw
    app.kubernetes.io/instance: {{ .Values.bucketName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: versitygw
      app.kubernetes.io/instance: {{ .Values.bucketName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: versitygw
        app.kubernetes.io/instance: {{ .Values.bucketName }}
    spec:
      containers:
        - name: versitygw
          envFrom:
            - secretRef:
                {{ if .Values.credentials.existingSecret.enabled }}
                name: {{ .Values.credentials.existingSecret.name }}
                {{ else }}
                name: {{ .Release.Name }}-credentials
                {{ end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          args:
          - "--port"
          - ":80"
          - "posix"
          - "--sidecar"
          - "/var/vgw/metadata"
          - "/var/vgw/data"
          volumeMounts:
          - name: data
            mountPath: /var/vgw/data
          - name: metadata
            mountPath: /var/vgw/metadata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata
