---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: versitygw
    app.kubernetes.io/instance: {{ .Values.bucketName }}
spec:
  accessModes: {{ .toYaml .Values.storage.data.accessModes | nindent 4 }}
  storageClassName: {{ .Values.storage.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: versitygw
    app.kubernetes.io/instance: {{ .Values.bucketName }}
spec:
  accessModes: {{ .toYaml .Values.storage.metadata.accessModes | nindent 4 }}
  storageClassName: {{ .Values.storage.metadata.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.metadata.size }}
