apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diskprep.fullname" . }}-script
  labels:
    app.kubernetes.io/name: {{ include "diskprep.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ensure-lvm.sh: |
{{ .Files.Get "files/ensure-lvm.sh" | indent 4 }}
