name: chart-testing

on:
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/chart-testing.yaml"
      - ".ct.yaml"
  push:
    branches: ["main", "master"]
    paths:
      - "charts/**"
      - ".github/workflows/chart-testing.yaml"
      - ".ct.yaml"

permissions:
  contents: read

jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: helm/chart-testing-action@v2

      - name: Lint
        run: ct lint --config .ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Install
        run: ct install --config .ct.yaml
